### ISSUE TITLE
Change Location Details Selections

### ISSUE THREAD

**Issue by jerrylin1218** [CleanOceanAction/coa_ui#24]
Current Behavior:
* Category | Location

Desired Behavior
* County | Town | Site
* cascading filter

**Comment by maithuvenkatesh** [comment]
The backend call for this has been implemented as part of the re-write of the flask app. Working on the UI work now using dummy data.

**Comment by mwilli20** [comment]
Will be pair programming this tomorrow evening, so hopefully this should be done before our next meeting.

**Comment by maithuvenkatesh** [comment]
We finished this feature. We need to deploy the backend changes but can demo this at the next meeting.

**Comment by mwilli20** [comment]
Will be handled in https://github.com/CleanOceanAction/coa_ui/pull/37

**Comment by mcampellone10** [comment]
The layout looks great, however, if I change either the county or site drop downs to select a new option, shouldn't we have the app clear out the previous selections to avoid confusion. Let me know if I can provide more color.

**Comment by mwilli20** [comment]
No definitely, I thought we did something for that, sounds like it should be a quick thing.

**Comment by mwilli20** [comment]
So we are clearing it out with undefined but the function used to take the undefined probably needs to return an empty label so it looks empty. Easy fix, I'll test it out later to make sure it looks right.

https://github.com/CleanOceanAction/coa_ui/blob/master/src/LocationDetails.js#L84
https://github.com/CleanOceanAction/coa_ui/blob/master/src/LocationDetails.js#L27
