### ISSUE TITLE
Look into maps for the UI

### ISSUE THREAD

**Issue by mwilli20** [CleanOceanAction/coa_ui#29]
There is a desire to look into a site via a map. Mapbox can allow up to 10,000 views for free in a month for a static view with markers overlayed . There is also a react module for this:

https://github.com/mapbox/batfish

**Comment by mwilli20** [comment]
We might want to put this one on hold for now.

**Comment by mcampellone10** [comment]
From COA on this specific enhancement request: "An additional feature that might be helpful (but would require more work) is to include a simple map of NJ that highlights the county that someone is looking at or has a line that marks the particular site. Spencer and I know these locations very well but understand that not everyone who is viewing the data has that same knowledge."

**Comment by mwilli20** [comment]
Replaced by https://github.com/CleanOceanAction/coa-superset
