### ISSUE TITLE
Enhance Pie Chart/Hierarchy breakdown

### ISSUE THREAD

**Issue by mwilli20** [CleanOceanAction/coa_ui#32]
The current visualization for the hierarchy leaves a bit to be desired.

Ideally this has a breakdown by top category, and then as you drill into each you can see the stats for each, and be able to pop back to a previous view. Each view should ideally have a legend so you can see what we are looking out instead of needing to rely on solely the tool tip.

The title should also be something like "Debris Breakdown" or something like that.

**Comment by mcampellone10** [comment]
From COA on this specific enhancement: "Instead, can it be in the form of a simple pie chart that shows the macro categories (plastic, metal, etc.) that then allows you to select one of those categories to see another pie chart with the percent makeup of the minor categories (i.e. plastic bottles under plastic)."
--> this is similar to the pie chart we had in V1 of the app that allows user to drill down into a specific category and see underlying sub categories.

**Comment by mwilli20** [comment]
This would need to be changed:

https://github.com/CleanOceanAction/coa_ui/blob/master/src/DebrisBreakdown.js#L646-L672

I might suggest we use https://nivo.rocks/waffle/ and then on drilling into a certain category create a seperate waffle chart for each of the layer. I can probably look into this one as well, as this really shouldn't be too bad.

**Comment by mwilli20** [comment]
Replaced byhttps://github.com/CleanOceanAction/coa-superset
